# Generated by Django 5.1.7 on 2025-03-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uploadedfile',
            table='uploaded_files',
        ),
    ]
