# Generated by Django 5.1.7 on 2025-03-07 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0002_alter_uploadedfile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uploadedfile',
            table=None,
        ),
    ]
