# Generated by Django 5.1.7 on 2025-03-07 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0003_alter_uploadedfile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uploadedfile',
            table='files',
        ),
    ]
