# Generated by Django 5.1.7 on 2025-04-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('UX Designer', 'Ux Designer'), ('Product Manager', 'Product Manager'), ('Frontend Developer', 'Frontend Developer'), ('Product Analyst', 'Product Analyst'), ('Product Owner', 'Product Owner')], default='Product Manager', max_length=32),
        ),
    ]
