# Generated by Django 5.1.7 on 2025-03-31 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Online Retail & Marketplace', 'Online Retail & Marketplace'), ('Fashion & Apparel', 'Fashion & Apparel'), ('Cosmetics & Beauty', 'Cosmetics & Beauty'), ('Electronics & Gadgets', 'Electronics & Gadgets'), ('Food & Grocery', 'Food & Grocery'), ('Toys & Baby Products', 'Toys & Baby Products'), ('Furniture & Home Decor', 'Furniture & Home Decor'), ('Jewelry & Accessories', 'Jewelry & Accessories'), ('Luxury Goods', 'Luxury Goods')], max_length=255)),
                ('landing_page', models.URLField(blank=True, null=True)),
                ('results_page', models.URLField(blank=True, null=True)),
                ('product_page', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Online Retail & Marketplace', 'Online Retail & Marketplace'), ('Fashion & Apparel', 'Fashion & Apparel'), ('Cosmetics & Beauty', 'Cosmetics & Beauty'), ('Electronics & Gadgets', 'Electronics & Gadgets'), ('Food & Grocery', 'Food & Grocery'), ('Toys & Baby Products', 'Toys & Baby Products'), ('Furniture & Home Decor', 'Furniture & Home Decor'), ('Jewelry & Accessories', 'Jewelry & Accessories'), ('Luxury Goods', 'Luxury Goods')], max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Onboard.rolemodel')),
            ],
        ),
    ]
