# Generated by Django 5.1.7 on 2025-03-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='shark',
            field=models.URLField(null=True),
        ),
    ]
