# Generated by Django 5.1.7 on 2025-03-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onboard', '0002_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='user',
            new_name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='page',
            name='file_path',
        ),
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(default='Unnamed File', max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='path',
            field=models.CharField(default='/default/path/to/file', max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('txt', 'Text File'), ('csv', 'CSV'), ('pdf', 'PDF'), ('jpg', 'JPG')], default='pdf', max_length=10),
        ),
        migrations.AddField(
            model_name='page',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('Landing Page', 'Landing Page'), ('Search Results Page', 'Search Results Page'), ('Product Page', 'Product Page')], default='Landing Page', max_length=50),
        ),
    ]
