# Generated by Django 5.1.7 on 2025-03-20 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Onboard', '0002_business_shark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='shark',
            new_name='role_model',
        ),
    ]
