# Generated by Django 5.1.7 on 2025-03-31 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Onboard', '0003_rename_user_page_uploaded_by_remove_page_file_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='path',
        ),
        migrations.RemoveField(
            model_name='page',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='page',
            name='uploaded_by',
        ),
    ]
