# Generated by Django 5.1.7 on 2025-03-31 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Onboard', '0004_remove_page_path_remove_page_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='type',
        ),
    ]
