# Generated by Django 5.1.7 on 2025-03-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onboard', '0005_remove_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
