# Generated by Django 5.1.7 on 2025-03-31 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onboard', '0006_page_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='name',
        ),
        migrations.AddField(
            model_name='page',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Onboard.business'),
        ),
    ]
