# Generated by Django 5.1.7 on 2025-03-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onboard', '0008_alter_rolemodel_landing_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodel',
            name='landing_page',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='product_page',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='results_page',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
