# Generated by Django 5.1.7 on 2025-04-01 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Onboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('txt', 'Text File'), ('csv', 'CSV'), ('json', 'JSON'), ('jpg', 'JPG')], max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('references_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Onboard.page')),
            ],
            options={
                'db_table': 'file_uploads',
            },
        ),
    ]
