# Generated by Django 5.1.7 on 2025-04-01 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageData', '0002_upload_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='name',
        ),
    ]
