# Generated by Django 5.1.7 on 2025-04-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageData', '0003_remove_upload_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='upload',
            name='name',
            field=models.CharField(default='unnamed file', max_length=255),
            preserve_default=False,
        ),
    ]
